#%RAML 1.0
traits:
  hasResponseItem: 
    queryParameters:
      <<param>>?: integer
    responses:
      200:
        body:
          application/json:
  hasNotFound:
    responses:
      404:
        body:
          application/json:
resourceTypes:
  item:
    usage: Use this resourceType to represent any single item
    get:
      is: [ hasResponseItem: { param: <<param>>}, hasNotFound ]
                      
title: DS
version: v1
protocols: [ HTTPS ]
baseUri: http://localhost:8081/api/{version}
mediaType: application/json

/day:
  type: { item: { param: dayNumber } }
/month:
  type: { item: { param: monthNumber } }